//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCareDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioAppointment
    {
        public int AudioId { get; set; }
        public int PatientId { get; set; }
        public byte[] Audio { get; set; }
        public string FileName { get; set; }
        public System.DateTime DateTime { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
        public int AppointmentId { get; set; }
    }
}
