//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCareDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodPressure
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public System.DateTime When { get; set; }
        public int Systolic { get; set; }
        public int Diastolic { get; set; }
        public int Pulse { get; set; }
        public Nullable<bool> IrregularHeartbeat { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
