//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCareDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string PlanName { get; set; }
        public string CoverageType { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public string GroupNumber { get; set; }
        public string SubscriberID { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public System.DateTime SubscriberDate { get; set; }
        public System.DateTime SubscriberDOB { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
