//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCareDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutritionInfo
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> Carbohydrates { get; set; }
        public Nullable<int> Protein { get; set; }
        public Nullable<int> TotalFat { get; set; }
        public Nullable<int> SaturatedFat { get; set; }
        public Nullable<int> MonounsaturatedFat { get; set; }
        public Nullable<int> PolyunsaturatedFat { get; set; }
        public Nullable<int> TransFat { get; set; }
        public Nullable<int> Sugars { get; set; }
        public Nullable<int> DietaryFiber { get; set; }
        public Nullable<int> Cholesterol { get; set; }
        public Nullable<int> Sodium { get; set; }
        public Nullable<int> Iron { get; set; }
        public Nullable<int> Magnesium { get; set; }
        public Nullable<int> Phosphorus { get; set; }
        public Nullable<int> Potassium { get; set; }
        public Nullable<int> Zinc { get; set; }
        public Nullable<int> VitaminA_RAE { get; set; }
        public Nullable<int> Vitamin_B6 { get; set; }
        public Nullable<int> Vitamin_B12 { get; set; }
        public Nullable<int> Vitamin_C { get; set; }
        public Nullable<int> Vitamin_D { get; set; }
        public Nullable<int> Vitamin_E { get; set; }
        public Nullable<int> Vitamin_K { get; set; }
        public Nullable<int> Niacin { get; set; }
        public Nullable<int> Riboflavin { get; set; }
        public Nullable<int> Thiamin { get; set; }
        public Nullable<int> Folate_DFE { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
    }
}
