//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHealthCareDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.BloodPressures = new HashSet<BloodPressure>();
            this.Conditions = new HashSet<Condition>();
            this.Contacts = new HashSet<Contact>();
            this.DietaryIntakes = new HashSet<DietaryIntake>();
            this.Distances = new HashSet<Distance>();
            this.Elevations = new HashSet<Elevation>();
            this.Heights = new HashSet<Height>();
            this.Insurances = new HashSet<Insurance>();
            this.Medications = new HashSet<Medication>();
            this.PatientNotes = new HashSet<PatientNote>();
            this.Steps = new HashSet<Step>();
            this.Weights = new HashSet<Weight>();
        }
    
        public int PatientId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public System.DateTime DOB { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public bool Gender { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
    
        public virtual ICollection<BloodPressure> BloodPressures { get; set; }
        public virtual ICollection<Condition> Conditions { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<DietaryIntake> DietaryIntakes { get; set; }
        public virtual ICollection<Distance> Distances { get; set; }
        public virtual ICollection<Elevation> Elevations { get; set; }
        public virtual ICollection<Height> Heights { get; set; }
        public virtual ICollection<Insurance> Insurances { get; set; }
        public virtual ICollection<Medication> Medications { get; set; }
        public virtual ICollection<PatientNote> PatientNotes { get; set; }
        public virtual ICollection<Step> Steps { get; set; }
        public virtual ICollection<Weight> Weights { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
